// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package on_photo
//

// Package on_photo is a generated GoMock package.
package on_photo

import (
	context "context"
	io "io"
	reflect "reflect"

	chathistory "github.com/reijo1337/ToxicBot/internal/features/chathistory"
	chatsettings "github.com/reijo1337/ToxicBot/internal/features/chatsettings"
	message "github.com/reijo1337/ToxicBot/internal/features/message"
	stats "github.com/reijo1337/ToxicBot/internal/features/stats"
	gomock "go.uber.org/mock/gomock"
	telebot "gopkg.in/telebot.v3"
)

// MockimageDescriber is a mock of imageDescriber interface.
type MockimageDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockimageDescriberMockRecorder
	isgomock struct{}
}

// MockimageDescriberMockRecorder is the mock recorder for MockimageDescriber.
type MockimageDescriberMockRecorder struct {
	mock *MockimageDescriber
}

// NewMockimageDescriber creates a new mock instance.
func NewMockimageDescriber(ctrl *gomock.Controller) *MockimageDescriber {
	mock := &MockimageDescriber{ctrl: ctrl}
	mock.recorder = &MockimageDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockimageDescriber) EXPECT() *MockimageDescriberMockRecorder {
	return m.recorder
}

// GenerateContent mocks base method.
func (m *MockimageDescriber) GenerateContent(ctx context.Context, prompt string, imageBytes []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateContent", ctx, prompt, imageBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateContent indicates an expected call of GenerateContent.
func (mr *MockimageDescriberMockRecorder) GenerateContent(ctx, prompt, imageBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateContent", reflect.TypeOf((*MockimageDescriber)(nil).GenerateContent), ctx, prompt, imageBytes)
}

// MockmessageGenerator is a mock of messageGenerator interface.
type MockmessageGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockmessageGeneratorMockRecorder
	isgomock struct{}
}

// MockmessageGeneratorMockRecorder is the mock recorder for MockmessageGenerator.
type MockmessageGeneratorMockRecorder struct {
	mock *MockmessageGenerator
}

// NewMockmessageGenerator creates a new mock instance.
func NewMockmessageGenerator(ctrl *gomock.Controller) *MockmessageGenerator {
	mock := &MockmessageGenerator{ctrl: ctrl}
	mock.recorder = &MockmessageGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageGenerator) EXPECT() *MockmessageGeneratorMockRecorder {
	return m.recorder
}

// GetMessageTextWithHistoryAndSteering mocks base method.
func (m *MockmessageGenerator) GetMessageTextWithHistoryAndSteering(history []chathistory.Entry, aiChance float32, forceAI bool, steering string) message.GenerationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageTextWithHistoryAndSteering", history, aiChance, forceAI, steering)
	ret0, _ := ret[0].(message.GenerationResult)
	return ret0
}

// GetMessageTextWithHistoryAndSteering indicates an expected call of GetMessageTextWithHistoryAndSteering.
func (mr *MockmessageGeneratorMockRecorder) GetMessageTextWithHistoryAndSteering(history, aiChance, forceAI, steering any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageTextWithHistoryAndSteering", reflect.TypeOf((*MockmessageGenerator)(nil).GetMessageTextWithHistoryAndSteering), history, aiChance, forceAI, steering)
}

// MocksettingsProvider is a mock of settingsProvider interface.
type MocksettingsProvider struct {
	ctrl     *gomock.Controller
	recorder *MocksettingsProviderMockRecorder
	isgomock struct{}
}

// MocksettingsProviderMockRecorder is the mock recorder for MocksettingsProvider.
type MocksettingsProviderMockRecorder struct {
	mock *MocksettingsProvider
}

// NewMocksettingsProvider creates a new mock instance.
func NewMocksettingsProvider(ctrl *gomock.Controller) *MocksettingsProvider {
	mock := &MocksettingsProvider{ctrl: ctrl}
	mock.recorder = &MocksettingsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksettingsProvider) EXPECT() *MocksettingsProviderMockRecorder {
	return m.recorder
}

// GetForChat mocks base method.
func (m *MocksettingsProvider) GetForChat(ctx context.Context, chatID int64) (*chatsettings.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForChat", ctx, chatID)
	ret0, _ := ret[0].(*chatsettings.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForChat indicates an expected call of GetForChat.
func (mr *MocksettingsProviderMockRecorder) GetForChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForChat", reflect.TypeOf((*MocksettingsProvider)(nil).GetForChat), ctx, chatID)
}

// MockhistoryBuffer is a mock of historyBuffer interface.
type MockhistoryBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockhistoryBufferMockRecorder
	isgomock struct{}
}

// MockhistoryBufferMockRecorder is the mock recorder for MockhistoryBuffer.
type MockhistoryBufferMockRecorder struct {
	mock *MockhistoryBuffer
}

// NewMockhistoryBuffer creates a new mock instance.
func NewMockhistoryBuffer(ctrl *gomock.Controller) *MockhistoryBuffer {
	mock := &MockhistoryBuffer{ctrl: ctrl}
	mock.recorder = &MockhistoryBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhistoryBuffer) EXPECT() *MockhistoryBufferMockRecorder {
	return m.recorder
}

// AddAll mocks base method.
func (m *MockhistoryBuffer) AddAll(chatID int64, entries ...chathistory.Entry) {
	m.ctrl.T.Helper()
	varargs := []any{chatID}
	for _, a := range entries {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddAll", varargs...)
}

// AddAll indicates an expected call of AddAll.
func (mr *MockhistoryBufferMockRecorder) AddAll(chatID any, entries ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{chatID}, entries...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAll", reflect.TypeOf((*MockhistoryBuffer)(nil).AddAll), varargs...)
}

// Get mocks base method.
func (m *MockhistoryBuffer) Get(chatID int64) []chathistory.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", chatID)
	ret0, _ := ret[0].([]chathistory.Entry)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockhistoryBufferMockRecorder) Get(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockhistoryBuffer)(nil).Get), chatID)
}

// Mockdownloader is a mock of downloader interface.
type Mockdownloader struct {
	ctrl     *gomock.Controller
	recorder *MockdownloaderMockRecorder
	isgomock struct{}
}

// MockdownloaderMockRecorder is the mock recorder for Mockdownloader.
type MockdownloaderMockRecorder struct {
	mock *Mockdownloader
}

// NewMockdownloader creates a new mock instance.
func NewMockdownloader(ctrl *gomock.Controller) *Mockdownloader {
	mock := &Mockdownloader{ctrl: ctrl}
	mock.recorder = &MockdownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdownloader) EXPECT() *MockdownloaderMockRecorder {
	return m.recorder
}

// FileByID mocks base method.
func (m *Mockdownloader) FileByID(fileID string) (telebot.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileByID", fileID)
	ret0, _ := ret[0].(telebot.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileByID indicates an expected call of FileByID.
func (mr *MockdownloaderMockRecorder) FileByID(fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileByID", reflect.TypeOf((*Mockdownloader)(nil).FileByID), fileID)
}

// MockfileReader is a mock of fileReader interface.
type MockfileReader struct {
	ctrl     *gomock.Controller
	recorder *MockfileReaderMockRecorder
	isgomock struct{}
}

// MockfileReaderMockRecorder is the mock recorder for MockfileReader.
type MockfileReaderMockRecorder struct {
	mock *MockfileReader
}

// NewMockfileReader creates a new mock instance.
func NewMockfileReader(ctrl *gomock.Controller) *MockfileReader {
	mock := &MockfileReader{ctrl: ctrl}
	mock.recorder = &MockfileReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileReader) EXPECT() *MockfileReaderMockRecorder {
	return m.recorder
}

// ReadFile mocks base method.
func (m *MockfileReader) ReadFile(file *telebot.File) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", file)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockfileReaderMockRecorder) ReadFile(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockfileReader)(nil).ReadFile), file)
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
	isgomock struct{}
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Warn mocks base method.
func (m *Mocklogger) Warn(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", arg0, arg1)
}

// Warn indicates an expected call of Warn.
func (mr *MockloggerMockRecorder) Warn(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*Mocklogger)(nil).Warn), arg0, arg1)
}

// WithError mocks base method.
func (m *Mocklogger) WithError(arg0 context.Context, arg1 error) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithError", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithError indicates an expected call of WithError.
func (mr *MockloggerMockRecorder) WithError(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithError", reflect.TypeOf((*Mocklogger)(nil).WithError), arg0, arg1)
}

// MockstatIncer is a mock of statIncer interface.
type MockstatIncer struct {
	ctrl     *gomock.Controller
	recorder *MockstatIncerMockRecorder
	isgomock struct{}
}

// MockstatIncerMockRecorder is the mock recorder for MockstatIncer.
type MockstatIncerMockRecorder struct {
	mock *MockstatIncer
}

// NewMockstatIncer creates a new mock instance.
func NewMockstatIncer(ctrl *gomock.Controller) *MockstatIncer {
	mock := &MockstatIncer{ctrl: ctrl}
	mock.recorder = &MockstatIncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatIncer) EXPECT() *MockstatIncerMockRecorder {
	return m.recorder
}

// Inc mocks base method.
func (m *MockstatIncer) Inc(ctx context.Context, chatID, userID int64, op stats.OperationType, opts ...stats.Option) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, userID, op}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Inc", varargs...)
}

// Inc indicates an expected call of Inc.
func (mr *MockstatIncerMockRecorder) Inc(ctx, chatID, userID, op any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, userID, op}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockstatIncer)(nil).Inc), varargs...)
}

// MockbotReplier is a mock of botReplier interface.
type MockbotReplier struct {
	ctrl     *gomock.Controller
	recorder *MockbotReplierMockRecorder
	isgomock struct{}
}

// MockbotReplierMockRecorder is the mock recorder for MockbotReplier.
type MockbotReplierMockRecorder struct {
	mock *MockbotReplier
}

// NewMockbotReplier creates a new mock instance.
func NewMockbotReplier(ctrl *gomock.Controller) *MockbotReplier {
	mock := &MockbotReplier{ctrl: ctrl}
	mock.recorder = &MockbotReplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbotReplier) EXPECT() *MockbotReplierMockRecorder {
	return m.recorder
}

// Reply mocks base method.
func (m *MockbotReplier) Reply(to *telebot.Message, what any, opts ...any) (*telebot.Message, error) {
	m.ctrl.T.Helper()
	varargs := []any{to, what}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Reply", varargs...)
	ret0, _ := ret[0].(*telebot.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reply indicates an expected call of Reply.
func (mr *MockbotReplierMockRecorder) Reply(to, what any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{to, what}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reply", reflect.TypeOf((*MockbotReplier)(nil).Reply), varargs...)
}
