// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package tagger
//

// Package tagger is a generated GoMock package.
package tagger

import (
	context "context"
	reflect "reflect"

	chatsettings "github.com/reijo1337/ToxicBot/internal/features/chatsettings"
	message "github.com/reijo1337/ToxicBot/internal/features/message"
	stats "github.com/reijo1337/ToxicBot/internal/features/stats"
	gomock "go.uber.org/mock/gomock"
)

// MocknicknameRepository is a mock of nicknameRepository interface.
type MocknicknameRepository struct {
	ctrl     *gomock.Controller
	recorder *MocknicknameRepositoryMockRecorder
	isgomock struct{}
}

// MocknicknameRepositoryMockRecorder is the mock recorder for MocknicknameRepository.
type MocknicknameRepositoryMockRecorder struct {
	mock *MocknicknameRepository
}

// NewMocknicknameRepository creates a new mock instance.
func NewMocknicknameRepository(ctrl *gomock.Controller) *MocknicknameRepository {
	mock := &MocknicknameRepository{ctrl: ctrl}
	mock.recorder = &MocknicknameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknicknameRepository) EXPECT() *MocknicknameRepositoryMockRecorder {
	return m.recorder
}

// GetEnabledNicknames mocks base method.
func (m *MocknicknameRepository) GetEnabledNicknames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledNicknames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledNicknames indicates an expected call of GetEnabledNicknames.
func (mr *MocknicknameRepositoryMockRecorder) GetEnabledNicknames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledNicknames", reflect.TypeOf((*MocknicknameRepository)(nil).GetEnabledNicknames))
}

// MockmessageGenerator is a mock of messageGenerator interface.
type MockmessageGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockmessageGeneratorMockRecorder
	isgomock struct{}
}

// MockmessageGeneratorMockRecorder is the mock recorder for MockmessageGenerator.
type MockmessageGeneratorMockRecorder struct {
	mock *MockmessageGenerator
}

// NewMockmessageGenerator creates a new mock instance.
func NewMockmessageGenerator(ctrl *gomock.Controller) *MockmessageGenerator {
	mock := &MockmessageGenerator{ctrl: ctrl}
	mock.recorder = &MockmessageGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageGenerator) EXPECT() *MockmessageGeneratorMockRecorder {
	return m.recorder
}

// GetMessageText mocks base method.
func (m *MockmessageGenerator) GetMessageText(ctx context.Context, prompt string, aiChance float32) message.GenerationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageText", ctx, prompt, aiChance)
	ret0, _ := ret[0].(message.GenerationResult)
	return ret0
}

// GetMessageText indicates an expected call of GetMessageText.
func (mr *MockmessageGeneratorMockRecorder) GetMessageText(ctx, prompt, aiChance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageText", reflect.TypeOf((*MockmessageGenerator)(nil).GetMessageText), ctx, prompt, aiChance)
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
	isgomock struct{}
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Warn mocks base method.
func (m *Mocklogger) Warn(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", arg0, arg1)
}

// Warn indicates an expected call of Warn.
func (mr *MockloggerMockRecorder) Warn(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*Mocklogger)(nil).Warn), arg0, arg1)
}

// WithError mocks base method.
func (m *Mocklogger) WithError(arg0 context.Context, arg1 error) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithError", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithError indicates an expected call of WithError.
func (mr *MockloggerMockRecorder) WithError(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithError", reflect.TypeOf((*Mocklogger)(nil).WithError), arg0, arg1)
}

// WithFields mocks base method.
func (m *Mocklogger) WithFields(arg0 context.Context, arg1 map[string]any) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithFields", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithFields indicates an expected call of WithFields.
func (mr *MockloggerMockRecorder) WithFields(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithFields", reflect.TypeOf((*Mocklogger)(nil).WithFields), arg0, arg1)
}

// Mockrandomizer is a mock of randomizer interface.
type Mockrandomizer struct {
	ctrl     *gomock.Controller
	recorder *MockrandomizerMockRecorder
	isgomock struct{}
}

// MockrandomizerMockRecorder is the mock recorder for Mockrandomizer.
type MockrandomizerMockRecorder struct {
	mock *Mockrandomizer
}

// NewMockrandomizer creates a new mock instance.
func NewMockrandomizer(ctrl *gomock.Controller) *Mockrandomizer {
	mock := &Mockrandomizer{ctrl: ctrl}
	mock.recorder = &MockrandomizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrandomizer) EXPECT() *MockrandomizerMockRecorder {
	return m.recorder
}

// Int63n mocks base method.
func (m *Mockrandomizer) Int63n(arg0 int64) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int63n", arg0)
	ret0, _ := ret[0].(int64)
	return ret0
}

// Int63n indicates an expected call of Int63n.
func (mr *MockrandomizerMockRecorder) Int63n(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int63n", reflect.TypeOf((*Mockrandomizer)(nil).Int63n), arg0)
}

// Intn mocks base method.
func (m *Mockrandomizer) Intn(arg0 int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Intn", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Intn indicates an expected call of Intn.
func (mr *MockrandomizerMockRecorder) Intn(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Intn", reflect.TypeOf((*Mockrandomizer)(nil).Intn), arg0)
}

// MockstatIncer is a mock of statIncer interface.
type MockstatIncer struct {
	ctrl     *gomock.Controller
	recorder *MockstatIncerMockRecorder
	isgomock struct{}
}

// MockstatIncerMockRecorder is the mock recorder for MockstatIncer.
type MockstatIncerMockRecorder struct {
	mock *MockstatIncer
}

// NewMockstatIncer creates a new mock instance.
func NewMockstatIncer(ctrl *gomock.Controller) *MockstatIncer {
	mock := &MockstatIncer{ctrl: ctrl}
	mock.recorder = &MockstatIncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatIncer) EXPECT() *MockstatIncerMockRecorder {
	return m.recorder
}

// Inc mocks base method.
func (m *MockstatIncer) Inc(ctx context.Context, chatID, userID int64, op stats.OperationType, opts ...stats.Option) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, userID, op}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Inc", varargs...)
}

// Inc indicates an expected call of Inc.
func (mr *MockstatIncerMockRecorder) Inc(ctx, chatID, userID, op any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, userID, op}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockstatIncer)(nil).Inc), varargs...)
}

// MocksettingsProvider is a mock of settingsProvider interface.
type MocksettingsProvider struct {
	ctrl     *gomock.Controller
	recorder *MocksettingsProviderMockRecorder
	isgomock struct{}
}

// MocksettingsProviderMockRecorder is the mock recorder for MocksettingsProvider.
type MocksettingsProviderMockRecorder struct {
	mock *MocksettingsProvider
}

// NewMocksettingsProvider creates a new mock instance.
func NewMocksettingsProvider(ctrl *gomock.Controller) *MocksettingsProvider {
	mock := &MocksettingsProvider{ctrl: ctrl}
	mock.recorder = &MocksettingsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksettingsProvider) EXPECT() *MocksettingsProviderMockRecorder {
	return m.recorder
}

// GetForChat mocks base method.
func (m *MocksettingsProvider) GetForChat(ctx context.Context, chatID int64) (*chatsettings.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForChat", ctx, chatID)
	ret0, _ := ret[0].(*chatsettings.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForChat indicates an expected call of GetForChat.
func (mr *MocksettingsProviderMockRecorder) GetForChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForChat", reflect.TypeOf((*MocksettingsProvider)(nil).GetForChat), ctx, chatID)
}
