// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package sheets is a generated GoMock package.
package sheets

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	spreadsheet_v2 "gopkg.in/Iwark/spreadsheet.v2"
)

// Mocksheets is a mock of sheets interface.
type Mocksheets struct {
	ctrl     *gomock.Controller
	recorder *MocksheetsMockRecorder
}

// MocksheetsMockRecorder is the mock recorder for Mocksheets.
type MocksheetsMockRecorder struct {
	mock *Mocksheets
}

// NewMocksheets creates a new mock instance.
func NewMocksheets(ctrl *gomock.Controller) *Mocksheets {
	mock := &Mocksheets{ctrl: ctrl}
	mock.recorder = &MocksheetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksheets) EXPECT() *MocksheetsMockRecorder {
	return m.recorder
}

// GetSpreadsheet mocks base method.
func (m *Mocksheets) GetSpreadsheet() (spreadsheet_v2.Spreadsheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpreadsheet")
	ret0, _ := ret[0].(spreadsheet_v2.Spreadsheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpreadsheet indicates an expected call of GetSpreadsheet.
func (mr *MocksheetsMockRecorder) GetSpreadsheet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpreadsheet", reflect.TypeOf((*Mocksheets)(nil).GetSpreadsheet))
}
