name: Build Docker reusable

on:
  workflow_call:
    inputs:
      binary_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}

    - name: chmod
      run: chmod +x ${{ inputs.binary_name }}
      
    - name: Build test docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: test-tag

    - name: Test run
      run: |
        timeout 5 docker run \
        -e TELEGRAM_TOKEN=${{ secrets.CI_TEST_TELEGRAM_TOKEN }} \
        -e IGOR_ID=${{ secrets.IGOR_ID }} \
        -e KIRILL_ID=${{ secrets.KIRILL_ID }} \
        -e MAX_ID=${{ secrets.MAX_ID }} \
        -e GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }} \
        -e GOOGLE_SPREADSHEET_ID=${{ secrets.GOOGLE_SPREADSHEET_ID }} \
        -e DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }} \
        -e DUCKDB_FILE_PATH=test.db \
        --rm test-tag || [ $? -eq 124 ]

    - name: Build and push
      if: ${{ inputs.push }}
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: 32133789756/toxicbot:${{ inputs.tag }}