name: Труба

on:
  workflow_run:
    workflows: [lint]
    branches: [master]
    types: [completed]

jobs:

  intro:
    runs-on: ubuntu-latest
    steps:
    - name: Intro
      run: echo "Эту трубу я посвещаю своему другу девпопсеру, любителю клопов и змей"

  binary:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=vendor -o bot -v cmd/main.go

    - name: Test
      run: go test -v ./...

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: go-binary
        path: bot

    - name: Upload dockerfile
      uses: actions/upload-artifact@v2
      with:
        name: Dockerfile
        path: Dockerfile
  
  docker:
    runs-on: ubuntu-latest
    needs: binary
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download binary
      uses: actions/download-artifact@v2
      with:
        name: go-binary

    - name: chmod
      run: chmod +x bot
    
    - name: Build and Push Docker
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: 32133789756/toxicbot
        registry: docker.io
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: deploy to vscale server using ansible
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yaml
        directory: deploy/
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [vscale_host]
          vscale ansible_host=37.228.116.131 ansible_user=root
        options: |
          --extra-vars "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} 
          IGOR_ID=${{ secrets.IGOR_ID }}
          STICKER_SETS=${{ secrets.STICKER_SETS != '' && secrets.STICKER_SETS || 'static_bulling_by_stickersthiefbot' }}
          GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_SPREADSHEET_ID=${{ secrets.GOOGLE_SPREADSHEET_ID }}"

