name: Труба

on:
  workflow_run:
    workflows: [lint]
    branches: [master]
    types: [completed]

jobs:

  intro:
    runs-on: ubuntu-latest
    steps:
    - name: Intro
      run: echo "Эту трубу я посвящаю своему другу девпопсеру, любителю клопов и змей"

  binary:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=vendor -o bot -v cmd/main.go

    - name: Test
      run: go test -race -v ./...

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: go-binary
        path: bot

    - name: Upload dockerfile
      uses: actions/upload-artifact@v2
      with:
        name: Dockerfile
        path: Dockerfile
  
  docker:
    runs-on: ubuntu-latest
    needs: binary
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Download binary
      uses: actions/download-artifact@v2
      with:
        name: go-binary

    - name: chmod
      run: chmod +x bot
      
    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: test-tag

    - name: Test run
      run: |
        timeout 5 docker run \
        -e TELEGRAM_TOKEN=${{ secrets.CI_TEST_TELEGRAM_TOKEN }} \
        -e IGOR_ID=${{ secrets.IGOR_ID }} \
        -e KIRILL_ID=${{ secrets.KIRILL_ID }} \
        -e MAX_ID=${{ secrets.MAX_ID }} \
        -e GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }} \
        -e GOOGLE_SPREADSHEET_ID=${{ secrets.GOOGLE_SPREADSHEET_ID }} \
        --rm test-tag || [ $? -eq 124 ]
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: 32133789756/toxicbot

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: deploy to vscale server using ansible
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yaml
        directory: deploy/
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [vscale_host]
          vscale ansible_host=37.228.116.131 ansible_user=root
        options: |
          --extra-vars "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} 
          IGOR_ID=${{ secrets.IGOR_ID }}
          MAX_ID=${{ secrets.MAX_ID }}
          KIRILL_ID=${{ secrets.KIRILL_ID }}
          STICKER_SETS=${{ secrets.STICKER_SETS != '' && secrets.STICKER_SETS || 'static_bulling_by_stickersthiefbot' }}
          GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_SPREADSHEET_ID=${{ secrets.GOOGLE_SPREADSHEET_ID }}"

