name: Труба

on: 
  push

jobs:
  intro:
    runs-on: ubuntu-latest
    steps:
    - name: Intro
      run: echo "Эту трубу я посвящаю своему другу девпопсеру, любителю клопов и змей"

  lint:
    uses: ./.github/workflows/lint.yml
  
  binary:
    needs: lint
    uses: ./.github/workflows/binary.yml
    secrets: inherit
    with:
      binary_name: bot
      artifact_name: go-binary
  
  docker:
    needs: binary
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      binary_name: bot
      artifact_name: go-binary
      tag: ${{ github.ref_name }}
      push: ${{ github.ref_type == 'tag' }}

  deploy:
    needs: docker
    if: ${{ github.ref_type == 'tag' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      docker_tag: ${{ github.ref_name }}
